### ISSUE TITLE
Sessions not working with Cloudflare Worker Proxy

### ISSUE THREAD

**Issue by lonelil** [pirsch-analytics/demo#4]
Session requests are not working and replying with Status 500, The error I got from real-time logs is "Unexpected end of JSON input".

**Comment by Kugelschieber** [comment]
Hey lonelil,

thanks for reporting! I'll take a look :)

**Comment by Kugelschieber** [comment]
Fixed it! You can simply copy and overwrite everything below `DO NOT CHANGE THE CODE BELOW!`:

https://raw.githubusercontent.com/pirsch-analytics/demo/master/cloudflare-workers/worker.js

**Comment by lonelil** [comment]
thanks!
